name: siamese-isic
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - pillow
      - matplotlib
      - scikit-learn
      - tqdm
      - pyyaml
      - torch
      - torchvision
      - torchaudio